### ISSUE TITLE
vibrate causing crashes

### ISSUE THREAD

**Issue by FGCMaid** [super-continent/acpr-buttplug#1]
kind of self explanatory, whenever a hit connect the device vibrates for a second then game crashes. happening to me and a friend a lot. is there any other set up not mentioned?

**Comment by super-continent** [comment]
this seems to be caused by a compiler optimization, it should work currently if built in debug mode, but since i dont want to deal with debugging a compiler transformation on the code im going to try and push out an update where it detects hits based on hitstop and other gamestate variables

**Comment by qdot** [comment]
Might also be worth offboarding the device control out to Intiface Central via the websocket connector, or at least having an option for that? That makes the Buttplug library codepaths way lighter (at the cost of having the game process now require network access instead of hardware access, so dunno if that'd cause permissions issues).

**Comment by super-continent** [comment]
that might be worth doing, currently i like having it integrated for ease of use, but if anyone ends up needing support for features inside that i'll absolutely consider it

**Comment by super-continent** [comment]
alright im building a new release that bases vibration on hitstop, currently there is 1 bug caused by this which is that the battle struct is left initialized, meaning sometimes devices will be stuck vibrating if the game exits the battle without all hitstop values resetting to 0

**Comment by super-continent** [comment]
release is up!
